### ISSUE TITLE
[Feature Request] Request for English version for the Appimage  索取英文版 (Appimage)

### ISSUE THREAD

**Issue by CrazyCoder009** [Pong420/Comic-Reader#24]
**Feature Request**
Hello there, I love the robust design and look of this reader, and would really appreciate it if you could release an English version of the software.
Thank you.
您好，我喜歡該閱讀器的堅固設計和外觀，如果您可以發布該軟件的英文版，則將非常感謝。
謝謝

**Comment by Pong420** [comment]
Sorry, the project has no longer maintained.
I will not create an english version

**Comment by CrazyCoder009** [comment]
Oh, that's sad to see. Thanks for the reply.
